# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KaKao_Login' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KaKao_Login
  pod 'KakaoSDK'
  pod 'naveridlogin-sdk-ios'
  pod 'GoogleSignIn'
  pod 'GoogleSignInSwiftSupport'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
end
